### ISSUE TITLE
FizzBuzz 구현

### ISSUE THREAD

**Issue by Seoin-Ahn** [UpstageAiLab5Group5/team_fizzbuzz#3]
## Description

fizzbuzz를 기능 구현을 위한 함수를 작성하세요.

## Tasks
- [x] fizz 함수 구현
- [x] buss 함수 구현
- [x] fizzbuss 함수 구현

**Comment by tjdwlek0** [comment]
감사합니다 바로 시작해주세요
